// export default [
//   {
//     name: "naomi",
//     descriptions: "some text",
//     price: 5000,
//     available: true,
//     onSale: true,
//   },
//   {
//     name: "kaly",
//     descriptions: "some text",
//     price: 2000,
//     available: true,
//     onSale: false,
//   },
//   {
//     name: "linda",
//     descriptions: "some text",
//     price: 12000,
//     available: true,
//     onSale: true,
//   },
//   {
//     name: "max",
//     descriptions: "some text",
//     price: 7000,
//     available: true,
//     onSale: false,
//   },
//   {
//     name: "kity",
//     descriptions: "some text",
//     price: 33000,
//     available: true,
//     onSale: true,
//   },
//   {
//     name: "dan",
//     descriptions: "some text",
//     price: 55000,
//     available: true,
//     onSale: false,
//   },
// ];

// --------------------

export default [
  {
    id: 1,
    amount: 250.75,
    date: "2024-07-01",
    business: "Alpha Corp",
    name: "Invoice Payment",
    type: "Credit",
    account: "Acc001",
  },
  {
    id: 2,
    amount: 1200.0,
    date: "2024-07-02",
    business: "Beta LLC",
    name: "Monthly Subscription",
    type: "Debit",
    account: "Acc002",
  },
  {
    id: 3,
    amount: 75.5,
    date: "2024-07-03",
    business: "Gamma Inc",
    name: "Consulting Fee",
    type: "Credit",
    account: "Acc003",
  },
  {
    id: 4,
    amount: 530.1,
    date: "2024-07-04",
    business: "Delta Ltd",
    name: "Service Payment",
    type: "Debit",
    account: "Acc004",
  },
  {
    id: 5,
    amount: 15.0,
    date: "2024-07-05",
    business: "Epsilon Co",
    name: "Miscellaneous Charges",
    type: "Credit",
    account: "Acc005",
  },
  {
    id: 6,
    amount: 300.25,
    date: "2024-07-06",
    business: "Zeta Corp",
    name: "Product Sale",
    type: "Debit",
    account: "Acc006",
  },
  {
    id: 7,
    amount: 420.0,
    date: "2024-07-07",
    business: "Eta LLC",
    name: "Refund",
    type: "Credit",
    account: "Acc007",
  },
  {
    id: 8,
    amount: 750.3,
    date: "2024-07-08",
    business: "Theta Inc",
    name: "Annual Fee",
    type: "Debit",
    account: "Acc008",
  },
  {
    id: 9,
    amount: 200.0,
    date: "2024-07-09",
    business: "Iota Ltd",
    name: "Donation",
    type: "Credit",
    account: "Acc009",
  },
  {
    id: 10,
    amount: 85.75,
    date: "2024-07-10",
    business: "Kappa Co",
    name: "Subscription Fee",
    type: "Debit",
    account: "Acc010",
  },
  {
    id: 11,
    amount: 600.0,
    date: "2024-07-11",
    business: "Lambda Corp",
    name: "Contract Payment",
    type: "Credit",
    account: "Acc011",
  },
  {
    id: 12,
    amount: 99.99,
    date: "2024-07-12",
    business: "Mu LLC",
    name: "Service Charge",
    type: "Debit",
    account: "Acc012",
  },
  {
    id: 13,
    amount: 50.0,
    date: "2024-07-13",
    business: "Nu Inc",
    name: "Event Fee",
    type: "Credit",
    account: "Acc013",
  },
  {
    id: 14,
    amount: 400.0,
    date: "2024-07-14",
    business: "Xi Ltd",
    name: "Training Fee",
    type: "Debit",
    account: "Acc014",
  },
  {
    id: 15,
    amount: 10.0,
    date: "2024-07-15",
    business: "Omicron Co",
    name: "Late Fee",
    type: "Credit",
    account: "Acc015",
  },
];
